version: '3.3'

services:
  registry:
    container_name: registry
    image: registry:2.8.3
    #ports:
    #  - 5000:5000
    volumes:
      - ./registry_data/config/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry_data/data:/var/lib/registry:rw
    #environment:
      #- "STANDALONE=true"
      #- "MIRROR_SOURCE=https://registry-1.docker.io"
      #- "MIRROR_SOURCE_INDEX=https://index.docker.io"
    env_file:  #only necessary if you want to change the password, see .env file
      - .env
    restart: unless-stopped
