---
services:
  kavita:
    image: lscr.io/linuxserver/kavita:0.8.4
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./kativa_data/config:/config
      - ./kativa_data/data:/data
    #ports:
    #  - 5000:5000
    restart: unless-stopped
