version: "3.7"
services:
  traggo:
    image: traggo/server:0.4.5
    container_name: traggo
    #ports:
    #  - 3030:3030
    environment:
      TRAGGO_DEFAULT_USER_NAME: "admin"
      TRAGGO_DEFAULT_USER_PASS: "mynewpassword"
    volumes:
      - ./traggo_data:/opt/traggo/data
    restart: unless-stopped
