version: '3.7'
services:
  web:
    image: 'gitlab/gitlab-ce:17.3.2-ce.0'
    restart: always
    hostname: 'localhost'
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - '8087:80'
      - '8444:443'
    volumes:
      - './gitlab_data/config:/etc/gitlab'
      - './gitlab_data/logs:/var/log/gitlab'
      - './gitlab_data/data:/var/opt/gitlab'
    networks:
      - gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - './gitlab_data/gitlab-runner:/etc/gitlab-runner'
    networks:
      - gitlab

networks:
  gitlab:
    name: gitlab-network
