apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-cm
data:
  promtail-config.yaml: |
    client:
      backoff_config:
        max_period: 5m
        max_retries: 10
        min_period: 500ms
      batchsize: 1048576
      batchwait: 1s
      external_labels: {}
      timeout: 10s
    positions:
      filename: /run/promtail/positions.yaml
    server:
      http_listen_port: 3101
    target_config:
      sync_period: 10s
    scrape_configs:
    - job_name: kubernetes-pods-name
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_namespace]
        regex: (default|cert-manager)
      - source_labels: [__meta_kubernetes_pod_label_name]
        target_label: __service__
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: __host__
      - action: drop
        regex: ''
        source_labels: [__service__]
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels: [__meta_kubernetes_namespace, __service__]
        target_label: job
      - action: replace
        source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - action: replace
        source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - action: replace
        source_labels: [__meta_kubernetes_pod_name]
        target_label: container
      - replacement: /var/log/containers/$1*.log
        separator: /
        source_labels: [__meta_kubernetes_pod_name]
        target_label: __path__

    - job_name: kubernetes-pods-app
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_namespace]
        regex: (default|cert-manager)
      - action: drop
        regex: .+
        source_labels: [__meta_kubernetes_pod_label_name]
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: __service__
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: __host__
      - action: drop
        regex: ''
        source_labels: [__service__]
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels: [__meta_kubernetes_namespace, __service__]
        target_label: job
      - action: replace
        source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - action: replace
        source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - action: replace
        source_labels: [__meta_kubernetes_pod_name]
        target_label: container
      - replacement: /var/log/containers/$1*.log
        separator: /
        source_labels: [__meta_kubernetes_pod_name]
        target_label: __path__

    - job_name: kubernetes-pods-direct-controllers
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_namespace]
        regex: (default|cert-manager)
      - action: drop
        regex: .+
        separator: ''
        source_labels: [__meta_kubernetes_pod_label_name, __meta_kubernetes_pod_label_app]
      - action: drop
        regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
        source_labels: [__meta_kubernetes_pod_controller_name]
      - source_labels: [__meta_kubernetes_pod_controller_name]
        target_label: __service__
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: __host__
      - action: drop
        regex: ''
        source_labels: [__service__]
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels: [__meta_kubernetes_namespace, __service__]
        target_label: job
      - action: replace
        source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - action: replace
        source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - action: replace
        source_labels: [__meta_kubernetes_pod_name]
        target_label: container
      - replacement: /var/log/containers/$1*.log
        separator: /
        source_labels: [__meta_kubernetes_pod_name]
        target_label: __path__
