apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail-ds
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail-sa
      containers:
      - name: promtail
        image: grafana/promtail:latest
        args:
          - '-config.file=/etc/promtail/promtail-config.yaml'
          - '-client.url=http://grafana.example.com:3100/loki/api/v1/push'
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
          readOnlyRootFilesystem: true
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
        ports:
          - name: http-metrics
            containerPort: 3101
            protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /etc/promtail
          - name: run
            mountPath: /run/promtail
          - name: docker
            readOnly: true
            mountPath: /var/lib/docker/containers
          - name: containers
            readOnly: true
            mountPath: /var/log/containers
          - name: pods
            readOnly: true
            mountPath: /var/log/pods
      volumes:
        - name: config
          configMap:
            name: promtail-cm
            defaultMode: 420
        - name: run
          hostPath:
            path: /run/promtail
            type: ''
        - name: docker
          hostPath:
            path: /var/lib/docker/containers
            type: ''
        - name: containers
          hostPath:
            path: /var/log/containers
            type: ''
        - name: pods
          hostPath:
            path: /var/log/pods
            type: ''