version: '3.3'
services:
    speedtest-tracker:
        image: ghcr.io/alexjustesen/speedtest-tracker:v0.18.7
        container_name: speedtest-tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
        volumes:
            - speedtest-app:/config
            - '/path/to/directory/web:/etc/ssl/web'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: postgres:16
        restart: always
        environment:
            - POSTGRES_DB=speedtest_tracker
            - POSTGRES_USER=speedy
            - POSTGRES_PASSWORD=password
        volumes:
            - speedtest-db:/var/lib/postgresql/data
volumes:
  speedtest-app:
  speedtest-db:
