---
version: "2.1"
services:
  hedgedoc:
    image: lscr.io/linuxserver/hedgedoc:1.10.3
    container_name: hedgedoc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - "DB_HOST=<hostname or ip>"
      - DB_PORT=3306
      - DB_USER=hedgedoc
      - "DB_PASS=<secret password>"
      - DB_NAME=hedgedoc
      - CMD_DOMAIN=localhost
      - CMD_URL_ADDPORT=false #optional
      - CMD_PROTOCOL_USESSL=false #optional
      - CMD_PORT=3000 #optional
      - CMD_ALLOW_ORIGIN=['localhost'] #optional
    volumes:
      - ./hedgedoc_data/config:/config
    #ports:
    #  - 3000:3000
    restart: unless-stopped
