---
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.21-ls257
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./calibre-web_data/config:/config
      - ./calibre-web_data/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
