---
version: "2.1"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:1.14.0.1-ls12
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
    #  - DOCKER_HUB_USERNAME=USER #optional
    #  - DOCKER_HUB_PASSWORD=PASS #optional
    #  - DOCKER_MTU=1500 #optional
    volumes:
      - ./kasm_data/opt:/opt
      - ./kasm_data/profiles:/profiles #optional
      #- /dev/input:/dev/input #optional
      #- /run/udev/data:/run/udev/data #optional
    #ports:
      #- 3000:3000
      #- 2443:443
    restart: on-failure
