---
version: '3.1'
services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: some-password
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data/data:/var/lib/postgresql/data
