---
version: '3.3'
services:
  authelia:
   image: authelia/authelia:4.38.11
   volumes:
      - ./authelia_data/config:/config
   ports:
      - 9091:9091
   restart: unless-stopped
   healthcheck:
      disable: true
   environment:
      - TZ=Etc/UTC
   depends_on:
      - redis

  redis:
    image: redis:alpine3.18
    volumes:
      - ./redis_data/data:/data
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC

