version: "2.1"
services:
  webtop:
    image: ghcr.io/linuxserver/webtop:ubuntu-mate-e5c32b8f-ls109
    container_name: webtop
    #privileged: true #optional but not needed unless you are running kde or i3 or other tools
    environment:
      - PUID=1000 # based on id
      - PGID=1000 # based on group
      - TZ=Etc/UTC # your timezone
    volumes:
      - ./webtop_data/config:/config #home directory
      #- /var/run/docker.sock:/var/run/docker.sock #optional only if you need access to docker winthin this container
    #ports:
      #- 3000:3000 # HTTP
      #- 8085:3001 # HTTPS
    shm_size: "4gb" #optional but set to 1GB or higher to prevent browser crashes
    #devices:
    #  - /dev/snd:/dev/snd #optional
    #restart: unless-stopped
    # env_file:  #only necessary if you want to change the password, see .env file
    #   - .env
