version: '3'

services:
  mkdocs:
    container_name: mkdocs
    image: squidfunk/mkdocs-material:9.5
    #ports:
    #  - "8000:8000"
    volumes:
      - ./mkdocs_data/docs:/docs
    restart: on-failure:5
