version: '3.8'

services:
  alloydb:
    image: google/alloydbomni:16.3.0

    environment:
      - POSTGRES_USER=${ALLOYDB_USER}
      - POSTGRES_PASSWORD=${ALLOYDB_PASSWORD}
      - POSTGRES_DB=${ALLOYDB_DB}
    ports:
      - "5432:5432"
    volumes:
      - alloydb_data:/var/lib/postgresql/data

volumes:
  alloydb_data:
