version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:7.84.14
    container_name: artifactory
    user: "${UID}:${GID}"
    #ports:
    # - 8089:8081
    volumes:
     - ./artifactory-oss_data/artifactory:/var/opt/jfrog/artifactory
    # Add extra Java options by uncommenting the following lines
    environment:
     - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
