---
version: "3"
services:
  gitea:
    image: gitea/gitea:1.23
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__PROTOCOL=https
      - GITEA__server__DOMAIN=git.example.com
      - GITEA__server__ROOT_URL=https://git.example.com/
      - GITEA__server__HTTP_PORT=443
      - GITEA__server__CERT_FILE=/data/certs/cert.pem
      - GITEA__server__KEY_FILE=/data/certs/key.pem
    volumes:
      - ./gitea_data/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./tls:/data/certs:ro:ro
    #ports:
    #  - "3000:3000"
    #  - "222:22"
    restart: unless-stopped
