services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:8.13.0
    #environment:
    #  - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
    #  - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    #  - PGADMIN_LISTEN_PORT=8080
    env_file:
      - .env
    #ports:
    #  - "8080:80"
    #volumes:
    #    - ./pgadmin_data/servers.json:/pgadmin4/servers.json
    #    - ./pgadmin_data/pgpass:/pgadmin4/pgpass
    restart: unless-stopped
