services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.5
    #environment:
    #  - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
    #  - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    env_file:
      - .env
    #ports:
    #  - "5050:80"
    restart: unless-stopped
