---
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    #environment:
      #- WG_HOST=some.example.com
      #- PASSWORD=some-password
      #- WG_PORT=51820
      #- WG_DEFAULT_ADDRESS=10.8.0.x
      #- WG_DEFAULT_DNS=192.168.60.10
    volumes:
      - ./wg-easy_data/wireguard.:/etc/wireguard
    #ports:
      #- "51820:51820/udp"
      #- "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg:
        ipv4_address: 10.42.42.42
        #ipv6_address: fdcc:ad94:bacf:61a3::2a
networks:
  wg:
    driver: bridge
    #enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - #subnet: fdcc:ad94:bacf:61a3::/64
...