version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      WATCHTOWER_SCHEDULE: "0 0 1 * * *"
      TZ: Etc/UTC
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_DEBUG: "true"
      #WATCHTOWER_NOTIFICATIONS: "email"
      #WATCHTOWER_NOTIFICATION_EMAIL_FROM: "docker@requena.fr"
      #WATCHTOWER_NOTIFICATION_EMAIL_TO: "admin@requena.fr"
      ## You have to use a network alias here, if you use your own certificate
      #WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "10.1.149.19"
      #WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: "8025"
      #WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - no-new-privileges:true

