version: '2'
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport:14
    container_name: teleport
#    entrypoint: /bin/sh
    hostname: localhost
    ports:
      - "3023:3023"
      - "3025:3025"
      - "3080:3080"
    volumes:
      - ./teleport_data/config:/etc/teleport
      - ./teleport_data/data:/var/lib/teleport
