version: '3.6'
services:
  checkmk:
    container_name: checkmk
    image: checkmk/check-mk-raw:2.3.0
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ulimits:
      nofile: 1024
    volumes:
      - ./checkmk_data/sites:/omd/sites
      - /etc/localtime:/etc/localtime:ro
    #ports:
    #  - "8080:5000"
    restart: unless-stopped

