---
version: '3.8'
services:
  cache:
    image: redis:7.4-alpine
    container_name: redis
    env_file: .env
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass some-password
    volumes:
      - ./redis_data/data:/data
