---
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:2.10.3
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./lidarr_config:/config
      - ./lidarr_music:/music #optional
      - ./lidarr_downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped