services:
  keycloak_db:
    image: postgres:15.6
    container_name: keycloak_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: unless-stopped


  keycloak_web:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak_web
    environment:
      KC_PROXY: edge
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: auth.example.com
      #KC_HOSTNAME_STRICT: false
      #KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - keycloak_db
    ports:
      - 8080:8080
    restart: unless-stopped


  oauth2_proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2_proxy
    volumes:
      - ./etc/ssl/certs/ca.cert.pem:/etc/ssl/certs/ca.cert
    environment:
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://auth.example.com/realms/dmz
      OAUTH2_PROXY_CLIENT_ID: webapps-client
      OAUTH2_PROXY_CLIENT_SECRET: <client_secret>
      OAUTH2_PROXY_COOKIE_SECRET: <cookie_secret>
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_NAME: _oauth2_proxy
      OAUTH2_PROXY_COOKIE_DOMAIN: .example.com  # Important for cross-domain SSO
      OAUTH2_PROXY_UPSTREAMS: "http://web:80"
      OAUTH2_PROXY_WHITELIST_DOMAINS: .example.com
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_REDIRECT_URL: https://web.example.com/oauth2/callback
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: true
      #OAUTH2_PROXY_SKIP_PROVIDER_TLS_VERIFY: true   # <- skip certificate verification
      OAUTH2_PROXY_CUSTOM_CA: /etc/ssl/certs/ca.cert
    #ports:
    #  - "4180:4180"
    restart: unless-stopped


volumes:
  postgres_data:
