version: "3.5"
services:
  postgres:
    image: postgres:16-alpine
    container_name: linkwarden_postgresql
    env_file: .env
    restart: always
    volumes:
      - ./linkwarden_data/pgdata:/var/lib/postgresql/data
    networks:
      - internal

  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    image: ghcr.io/linkwarden/linkwarden:v2.7.1
    container_name: linkwarden
    #ports:
    #  - 3000:3000
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
